name: linux_system_migrator
description: "A tool to help migrate linux systems to other linux variants."

# Prevent accidental publishing to pub.dev.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  fluent_ui: ^4.8.7
  window_manager: ^0.3.8
  dartssh2: ^2.8.2
  network_tools: ^5.0.2
  pool: ^1.5.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
